"""Upgrade the existing audit log table without discarding legacy rows.

Revision ID: 20260727_0002
Revises: 20260727_0001
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260727_0002"
down_revision = "20260727_0001"
branch_labels = None
depends_on = None


def _drop_foreign_key_for(column_name: str) -> None:
    inspector = sa.inspect(op.get_bind())
    for foreign_key in inspector.get_foreign_keys("audit_logs"):
        if foreign_key.get("constrained_columns") == [column_name]:
            name = foreign_key.get("name")
            if name:
                op.drop_constraint(name, "audit_logs", type_="foreignkey")


def upgrade() -> None:
    _drop_foreign_key_for("user_id")

    op.alter_column(
        "audit_logs",
        "user_id",
        new_column_name="actor_user_id",
        existing_type=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "module",
        new_column_name="resource",
        existing_type=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "performed_at",
        new_column_name="legacy_performed_at",
        existing_type=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "actor_email",
        existing_type=sa.String(length=100),
        type_=sa.String(length=320),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "resource",
        existing_type=sa.String(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "target",
        existing_type=sa.String(length=100),
        type_=sa.String(length=500),
        existing_nullable=True,
    )

    op.add_column(
        "audit_logs",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "audit_logs",
        sa.Column("actor_role", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("resource_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("status", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("description", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("ip_address", sa.String(length=45), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("user_agent", sa.String(length=512), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("request_id", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Legacy performed_at was generated by the database at insertion time.
    # Interpret it using the database's configured timezone, preserving its
    # original instant rather than replacing it with the migration time.
    op.execute(
        """
        UPDATE audit_logs
        SET occurred_at = legacy_performed_at AT TIME ZONE current_setting('TIMEZONE'),
            created_at = legacy_performed_at AT TIME ZONE current_setting('TIMEZONE')
        WHERE legacy_performed_at IS NOT NULL
        """
    )
    op.alter_column(
        "audit_logs",
        "occurred_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
        server_default=sa.text("now()"),
    )

    op.create_foreign_key(
        "fk_audit_logs_actor_user_id_users",
        "audit_logs",
        "users",
        ["actor_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ck_audit_logs_status",
        "audit_logs",
        "status IS NULL OR status IN ('SUCCESS', 'FAILURE')",
    )
    op.create_index(
        "ix_audit_logs_occurred_at",
        "audit_logs",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_actor_user_id",
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_actor_email",
        "audit_logs",
        ["actor_email"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_action",
        "audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_resource",
        "audit_logs",
        ["resource"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_status",
        "audit_logs",
        ["status"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_audit_logs_status", table_name="audit_logs")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_email", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_occurred_at", table_name="audit_logs")
    op.drop_constraint("ck_audit_logs_status", "audit_logs", type_="check")
    _drop_foreign_key_for("actor_user_id")

    op.drop_column("audit_logs", "created_at")
    op.drop_column("audit_logs", "metadata")
    op.drop_column("audit_logs", "request_id")
    op.drop_column("audit_logs", "user_agent")
    op.drop_column("audit_logs", "ip_address")
    op.drop_column("audit_logs", "description")
    op.drop_column("audit_logs", "status")
    op.drop_column("audit_logs", "resource_id")
    op.drop_column("audit_logs", "actor_role")
    op.drop_column("audit_logs", "occurred_at")

    op.alter_column(
        "audit_logs",
        "target",
        existing_type=sa.String(length=500),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "resource",
        existing_type=sa.String(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "actor_email",
        existing_type=sa.String(length=320),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "legacy_performed_at",
        new_column_name="performed_at",
        existing_type=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "resource",
        new_column_name="module",
        existing_type=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "actor_user_id",
        new_column_name="user_id",
        existing_type=sa.Integer(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "fk_audit_logs_user_id_users",
        "audit_logs",
        "users",
        ["user_id"],
        ["id"],
    )
